import { validateRapidDiagnosticForm } from "./schema";

const REVIEW = {
  status: "published",
  license: "original",
  reviewer: "AI ACT Tutor content review",
  reviewedAt: "2026-07-12",
} as const;

export const RAPID_DIAGNOSTIC_FORM = validateRapidDiagnosticForm({
  id: "rapid-core-form",
  version: "rapid-core-v1",
  mode: "rapid",
  title: "Reviewed rapid diagnostic",
  estimatedMinutes: 25,
  questions: [
    {
      id: "eng-boundaries-1",
      version: 1,
      section: "english",
      category: "Production of Writing",
      primarySkill: "sentence-boundaries",
      skillLabel: "Sentence boundaries",
      difficulty: "medium",
      stimulus:
        "The telescope was finally repaired ___ the astronomy club scheduled an observation night.",
      prompt:
        "Which option correctly joins the two independent clauses at the blank?",
      choices: [
        { id: "a", text: ", the" },
        { id: "b", text: "; the" },
        { id: "c", text: " the" },
        { id: "d", text: ", which the" },
      ],
      expectedSeconds: 45,
      correctChoiceId: "b",
      rationale:
        "Both sides of the blank are complete sentences. A semicolon can join two closely related independent clauses without a coordinating conjunction.",
      content: REVIEW,
    },
    {
      id: "eng-boundaries-2",
      version: 1,
      section: "english",
      category: "Knowledge of Language",
      primarySkill: "sentence-boundaries",
      skillLabel: "Sentence boundaries",
      difficulty: "medium",
      stimulus:
        "Although the rain stopped before noon. The trail remained muddy for the afternoon hike.",
      prompt:
        "Which revision fixes the sentence-boundary error while preserving the meaning?",
      choices: [
        {
          id: "a",
          text: "Although the rain stopped before noon. The trail remained muddy for the afternoon hike.",
        },
        {
          id: "b",
          text: "Although the rain stopped before noon, the trail remained muddy for the afternoon hike.",
        },
        {
          id: "c",
          text: "The rain stopped before noon, the trail remained muddy for the afternoon hike.",
        },
        {
          id: "d",
          text: "Stopping before noon. The rain left the trail muddy for the afternoon hike.",
        },
      ],
      expectedSeconds: 50,
      correctChoiceId: "b",
      rationale:
        "The opening dependent clause beginning with “Although” must be attached to the independent clause with a comma.",
      content: REVIEW,
    },
    {
      id: "eng-concision-1",
      version: 1,
      section: "english",
      category: "Knowledge of Language",
      primarySkill: "concision-and-redundancy",
      skillLabel: "Concision and redundancy",
      difficulty: "easy",
      stimulus: "Each individual runner received a medal after finishing.",
      prompt:
        "Which revision is the most concise without changing the sentence's meaning?",
      choices: [
        {
          id: "a",
          text: "Every separate individual runner received a medal after finishing.",
        },
        { id: "b", text: "Each runner received a medal after finishing." },
        {
          id: "c",
          text: "Each individual runner personally received a medal after finishing.",
        },
        {
          id: "d",
          text: "After finishing, each and every individual runner received a medal.",
        },
      ],
      expectedSeconds: 40,
      correctChoiceId: "b",
      rationale:
        "“Each” already refers to runners one at a time, so “individual” adds no useful meaning.",
      content: REVIEW,
    },
    {
      id: "eng-concision-2",
      version: 1,
      section: "english",
      category: "Knowledge of Language",
      primarySkill: "concision-and-redundancy",
      skillLabel: "Concision and redundancy",
      difficulty: "medium",
      stimulus:
        "The reason the bus arrived late was because a fallen branch blocked the road.",
      prompt: "Which revision states the idea most directly and grammatically?",
      choices: [
        {
          id: "a",
          text: "The bus arrived late because a fallen branch blocked the road.",
        },
        {
          id: "b",
          text: "The reason why the bus arrived late was due to the fact that a fallen branch blocked the road.",
        },
        {
          id: "c",
          text: "Because of a fallen branch being what blocked the road, this was the reason the bus arrived late.",
        },
        {
          id: "d",
          text: "The bus, for the reason of a fallen branch, arrived late because the road was blocked.",
        },
      ],
      expectedSeconds: 45,
      correctChoiceId: "a",
      rationale:
        "The direct subject-verb structure removes the redundant pairing of “the reason” with “because.”",
      content: REVIEW,
    },
    {
      id: "eng-commas-1",
      version: 1,
      section: "english",
      category: "Conventions of Standard English",
      primarySkill: "punctuation-and-commas",
      skillLabel: "Punctuation and commas",
      difficulty: "easy",
      stimulus:
        "After rehearsing for three weeks the student orchestra performed the new piece.",
      prompt: "Where should a comma be added to make the sentence correct?",
      choices: [
        { id: "a", text: "After rehearsing, for three weeks the student orchestra performed the new piece." },
        { id: "b", text: "After rehearsing for three weeks, the student orchestra performed the new piece." },
        { id: "c", text: "After rehearsing for three weeks the student orchestra, performed the new piece." },
        { id: "d", text: "No comma is needed." },
      ],
      expectedSeconds: 45,
      correctChoiceId: "b",
      rationale:
        "A comma follows the introductory prepositional phrase so readers can clearly identify where the main clause begins.",
      content: REVIEW,
    },
    {
      id: "eng-commas-2",
      version: 1,
      section: "english",
      category: "Conventions of Standard English",
      primarySkill: "punctuation-and-commas",
      skillLabel: "Punctuation and commas",
      difficulty: "medium",
      stimulus:
        "Mina packed a flashlight, a map and a rain jacket for the hike.",
      prompt: "Which revision uses commas consistently in the series?",
      choices: [
        { id: "a", text: "Mina packed a flashlight a map, and a rain jacket for the hike." },
        { id: "b", text: "Mina packed, a flashlight, a map and a rain jacket for the hike." },
        { id: "c", text: "Mina packed a flashlight, a map, and a rain jacket for the hike." },
        { id: "d", text: "Mina packed a flashlight a map and a rain jacket, for the hike." },
      ],
      expectedSeconds: 45,
      correctChoiceId: "c",
      rationale:
        "The three listed items are separated with commas, including the comma before the coordinating conjunction.",
      content: REVIEW,
    },
    {
      id: "eng-transitions-1",
      version: 1,
      section: "english",
      category: "Production of Writing",
      primarySkill: "logical-transitions",
      skillLabel: "Logical transitions",
      difficulty: "medium",
      stimulus:
        "The community garden had very little space. ___, volunteers grew herbs in stacked planters along the fence.",
      prompt: "Which transition most logically completes the sentence?",
      choices: [
        { id: "a", text: "For example" },
        { id: "b", text: "Nevertheless" },
        { id: "c", text: "Similarly" },
        { id: "d", text: "In conclusion" },
      ],
      expectedSeconds: 45,
      correctChoiceId: "b",
      rationale:
        "The second sentence describes what volunteers accomplished despite the limitation, so a contrast transition is required.",
      content: REVIEW,
    },
    {
      id: "eng-transitions-2",
      version: 1,
      section: "english",
      category: "Production of Writing",
      primarySkill: "logical-transitions",
      skillLabel: "Logical transitions",
      difficulty: "medium",
      stimulus:
        "The first prototype used a heavy steel frame. The second prototype, ___, used lightweight aluminum.",
      prompt: "Which transition best emphasizes the difference between the prototypes?",
      choices: [
        { id: "a", text: "in contrast" },
        { id: "b", text: "for instance" },
        { id: "c", text: "therefore" },
        { id: "d", text: "in addition" },
      ],
      expectedSeconds: 45,
      correctChoiceId: "a",
      rationale:
        "The materials differ in weight and type, so “in contrast” accurately signals the comparison.",
      content: REVIEW,
    },
    {
      id: "math-linear-1",
      version: 1,
      section: "math",
      category: "Preparing for Higher Math",
      primarySkill: "linear-equations",
      skillLabel: "Linear equations",
      difficulty: "easy",
      prompt: "What value of x satisfies 3x − 7 = 20?",
      choices: [
        { id: "a", text: "4" },
        { id: "b", text: "7" },
        { id: "c", text: "9" },
        { id: "d", text: "13" },
      ],
      expectedSeconds: 50,
      correctChoiceId: "c",
      rationale:
        "Add 7 to both sides to get 3x = 27, then divide by 3. Therefore, x = 9.",
      content: REVIEW,
    },
    {
      id: "math-linear-2",
      version: 1,
      section: "math",
      category: "Integrating Essential Skills",
      primarySkill: "linear-equations",
      skillLabel: "Linear equations",
      difficulty: "medium",
      prompt:
        "A game café charges a $4 entry fee plus $3 for each game played. If the total bill is $19, how many games were played?",
      choices: [
        { id: "a", text: "4" },
        { id: "b", text: "5" },
        { id: "c", text: "6" },
        { id: "d", text: "7" },
      ],
      expectedSeconds: 70,
      correctChoiceId: "b",
      rationale:
        "The equation is 4 + 3g = 19. Subtracting 4 gives 3g = 15, so g = 5.",
      content: REVIEW,
    },
    {
      id: "math-functions-1",
      version: 1,
      section: "math",
      category: "Preparing for Higher Math",
      primarySkill: "functions-and-modeling",
      skillLabel: "Functions and modeling",
      difficulty: "medium",
      prompt: "If f(x) = 2x² − 3, what is f(3)?",
      choices: [
        { id: "a", text: "9" },
        { id: "b", text: "12" },
        { id: "c", text: "15" },
        { id: "d", text: "33" },
      ],
      expectedSeconds: 55,
      correctChoiceId: "c",
      rationale: "Substitute 3 for x: 2(3²) − 3 = 2(9) − 3 = 15.",
      content: REVIEW,
    },
    {
      id: "math-functions-2",
      version: 1,
      section: "math",
      category: "Integrating Essential Skills",
      primarySkill: "functions-and-modeling",
      skillLabel: "Functions and modeling",
      difficulty: "medium",
      stimulus: "A linear function contains the points (1, 5) and (3, 13).",
      prompt: "What is the slope of the function?",
      choices: [
        { id: "a", text: "2" },
        { id: "b", text: "4" },
        { id: "c", text: "6" },
        { id: "d", text: "8" },
      ],
      expectedSeconds: 60,
      correctChoiceId: "b",
      rationale:
        "Slope is the change in y divided by the change in x: (13 − 5) ÷ (3 − 1) = 8 ÷ 2 = 4.",
      content: REVIEW,
    },
    {
      id: "math-percent-1",
      version: 1,
      section: "math",
      category: "Integrating Essential Skills",
      primarySkill: "ratios-and-percent",
      skillLabel: "Ratios and percent",
      difficulty: "easy",
      prompt: "A $60 backpack is discounted by 25%. What is the sale price?",
      choices: [
        { id: "a", text: "$15" },
        { id: "b", text: "$35" },
        { id: "c", text: "$45" },
        { id: "d", text: "$55" },
      ],
      expectedSeconds: 55,
      correctChoiceId: "c",
      rationale:
        "Twenty-five percent of $60 is $15. Subtracting the discount gives a sale price of $45.",
      content: REVIEW,
    },
    {
      id: "math-percent-2",
      version: 1,
      section: "math",
      category: "Integrating Essential Skills",
      primarySkill: "ratios-and-percent",
      skillLabel: "Ratios and percent",
      difficulty: "medium",
      prompt:
        "A paint mixture uses blue and white paint in a ratio of 3:2. If 12 cups of blue paint are used, how many cups of white paint are needed?",
      choices: [
        { id: "a", text: "6" },
        { id: "b", text: "8" },
        { id: "c", text: "10" },
        { id: "d", text: "18" },
      ],
      expectedSeconds: 65,
      correctChoiceId: "b",
      rationale:
        "Twelve cups is four times the ratio's 3 blue parts, so the 2 white parts also scale by four to 8 cups.",
      content: REVIEW,
    },
    {
      id: "math-geometry-1",
      version: 1,
      section: "math",
      category: "Integrating Essential Skills",
      primarySkill: "geometry-and-measurement",
      skillLabel: "Geometry and measurement",
      difficulty: "easy",
      prompt:
        "A rectangle is 9 centimeters long and 4 centimeters wide. What is its area?",
      choices: [
        { id: "a", text: "13 square centimeters" },
        { id: "b", text: "26 square centimeters" },
        { id: "c", text: "36 square centimeters" },
        { id: "d", text: "72 square centimeters" },
      ],
      expectedSeconds: 45,
      correctChoiceId: "c",
      rationale:
        "The area of a rectangle is length times width, so 9 × 4 = 36 square centimeters.",
      content: REVIEW,
    },
    {
      id: "math-geometry-2",
      version: 1,
      section: "math",
      category: "Preparing for Higher Math",
      primarySkill: "geometry-and-measurement",
      skillLabel: "Geometry and measurement",
      difficulty: "medium",
      prompt:
        "A right triangle has legs of length 6 and 8. What is the length of its hypotenuse?",
      choices: [
        { id: "a", text: "7" },
        { id: "b", text: "10" },
        { id: "c", text: "12" },
        { id: "d", text: "14" },
      ],
      expectedSeconds: 65,
      correctChoiceId: "b",
      rationale:
        "By the Pythagorean theorem, the hypotenuse is √(6² + 8²) = √100 = 10.",
      content: REVIEW,
    },
    {
      id: "read-central-1",
      version: 1,
      section: "reading",
      category: "Key Ideas and Details",
      primarySkill: "central-ideas-and-details",
      skillLabel: "Central ideas and details",
      difficulty: "medium",
      stimulus:
        "A neighborhood library began lending vegetable seeds from a small cabinet near its entrance. At first, few visitors used it. The librarians then added planting labels and held short weekend workshops. By midsummer, the cabinet emptied weekly, and several gardeners returned seeds from their strongest plants.",
      prompt: "Which statement best expresses the passage's central idea?",
      choices: [
        { id: "a", text: "Libraries should replace books with community gardening supplies." },
        { id: "b", text: "The seed program became more useful after the library added guidance and instruction." },
        { id: "c", text: "Weekend workshops are the only effective way to teach gardening." },
        { id: "d", text: "The gardeners returned every seed they borrowed from the library." },
      ],
      expectedSeconds: 75,
      correctChoiceId: "b",
      rationale:
        "The passage contrasts low initial use with strong participation after labels and workshops were added.",
      content: REVIEW,
    },
    {
      id: "read-central-2",
      version: 1,
      section: "reading",
      category: "Key Ideas and Details",
      primarySkill: "central-ideas-and-details",
      skillLabel: "Central ideas and details",
      difficulty: "easy",
      stimulus:
        "The school cafeteria installed sound-absorbing panels along one wall. Before the change, a meter regularly recorded lunch-hour noise above 85 decibels. After installation, the average fell to 72 decibels, and students in a survey reported that conversations required less shouting.",
      prompt: "Which conclusion is best supported by the passage?",
      choices: [
        { id: "a", text: "The panels reduced measured noise and made conversation easier." },
        { id: "b", text: "The cafeteria became completely silent during lunch." },
        { id: "c", text: "Students began eating lunch more quickly after the installation." },
        { id: "d", text: "Every school should install the same brand of acoustic panel." },
      ],
      expectedSeconds: 65,
      correctChoiceId: "a",
      rationale:
        "Both the meter reading and student survey directly support reduced noise and easier conversation.",
      content: REVIEW,
    },
    {
      id: "read-inference-1",
      version: 1,
      section: "reading",
      category: "Craft and Structure",
      primarySkill: "supported-inference",
      skillLabel: "Supported inference",
      difficulty: "medium",
      stimulus:
        "A neighborhood library began lending vegetable seeds from a small cabinet near its entrance. At first, few visitors used it. The librarians then added planting labels and held short weekend workshops. By midsummer, the cabinet emptied weekly, and several gardeners returned seeds from their strongest plants.",
      prompt:
        "The passage most strongly suggests that some visitors initially avoided the seed cabinet because they:",
      choices: [
        { id: "a", text: "did not know how to use the seeds successfully." },
        { id: "b", text: "believed the seeds were too expensive." },
        { id: "c", text: "wanted the library to offer flower seeds instead." },
        { id: "d", text: "were not allowed to enter the library on weekends." },
      ],
      expectedSeconds: 75,
      correctChoiceId: "a",
      rationale:
        "Use increased after the library provided labels and instruction, supporting the inference that uncertainty was an early barrier.",
      content: REVIEW,
    },
    {
      id: "read-inference-2",
      version: 1,
      section: "reading",
      category: "Craft and Structure",
      primarySkill: "supported-inference",
      skillLabel: "Supported inference",
      difficulty: "medium",
      stimulus:
        "Ceramic artist Lena Ortiz keeps several cracked bowls on a shelf above her worktable. She labels each one with the clay mixture, kiln temperature, and glaze used. Before beginning a new batch, she often studies those labels and runs a small test tile through the kiln.",
      prompt:
        "It can reasonably be inferred that Ortiz keeps the cracked bowls because she:",
      choices: [
        { id: "a", text: "plans to sell them at a lower price." },
        { id: "b", text: "uses them to learn from earlier results." },
        { id: "c", text: "prefers cracked bowls to finished work." },
        { id: "d", text: "has no room to store new materials." },
      ],
      expectedSeconds: 70,
      correctChoiceId: "b",
      rationale:
        "Her detailed labels and later test tiles show that the failed pieces function as records for improving future batches.",
      content: REVIEW,
    },
    {
      id: "read-evidence-1",
      version: 1,
      section: "reading",
      category: "Key Ideas and Details",
      primarySkill: "textual-evidence-and-details",
      skillLabel: "Textual evidence and details",
      difficulty: "medium",
      stimulus:
        "To test whether shade affected soil moisture, Priya placed identical pots in three locations. The pot in full sun lost 120 grams of water over two days, the pot in partial shade lost 75 grams, and the pot in full shade lost 42 grams. Each pot began with the same soil and water mass.",
      prompt: "Which detail most directly supports the claim that shade reduced water loss?",
      choices: [
        { id: "a", text: "The pots were identical." },
        { id: "b", text: "Each pot began with the same soil." },
        { id: "c", text: "The full-shade pot lost 42 grams while the full-sun pot lost 120 grams." },
        { id: "d", text: "The test lasted two days." },
      ],
      expectedSeconds: 70,
      correctChoiceId: "c",
      rationale:
        "The direct comparison between the shaded and sunny pots provides the measured evidence for reduced water loss.",
      content: REVIEW,
    },
    {
      id: "read-evidence-2",
      version: 1,
      section: "reading",
      category: "Key Ideas and Details",
      primarySkill: "textual-evidence-and-details",
      skillLabel: "Textual evidence and details",
      difficulty: "easy",
      stimulus:
        "The city added a protected bicycle lane on Oak Street in April. A traffic count in March recorded 180 cyclists during the morning commute. The same count in June recorded 310 cyclists. During that period, the number of car lanes and nearby bus routes did not change.",
      prompt: "According to the passage, how many more cyclists were counted in June than in March?",
      choices: [
        { id: "a", text: "90" },
        { id: "b", text: "120" },
        { id: "c", text: "130" },
        { id: "d", text: "490" },
      ],
      expectedSeconds: 55,
      correctChoiceId: "c",
      rationale:
        "The passage gives counts of 310 and 180; subtracting them shows an increase of 130 cyclists.",
      content: REVIEW,
    },
    {
      id: "read-purpose-1",
      version: 1,
      section: "reading",
      category: "Craft and Structure",
      primarySkill: "author-purpose-and-structure",
      skillLabel: "Author purpose and structure",
      difficulty: "medium",
      stimulus:
        "Most maps present rivers as fixed blue lines, but rivers continually reshape their channels. During floods, fast water can carve a shortcut across a bend. Sediment then accumulates in the older route, sometimes leaving a curved lake where the bend once flowed.",
      prompt: "The author's main purpose is to:",
      choices: [
        { id: "a", text: "argue that printed maps should never show rivers." },
        { id: "b", text: "explain one way a river's path can change over time." },
        { id: "c", text: "compare the depths of rivers and lakes." },
        { id: "d", text: "describe how to remain safe during a flood." },
      ],
      expectedSeconds: 70,
      correctChoiceId: "b",
      rationale:
        "The passage explains a sequence in which floodwater creates a shortcut and sediment closes the former bend.",
      content: REVIEW,
    },
    {
      id: "read-purpose-2",
      version: 1,
      section: "reading",
      category: "Craft and Structure",
      primarySkill: "author-purpose-and-structure",
      skillLabel: "Author purpose and structure",
      difficulty: "medium",
      stimulus:
        "At first, the repair team suspected the museum clock's motor. They replaced it, but the clock still lost several minutes each day. Next they inspected the gears and found no damage. Only after measuring the wall did they discover that afternoon sunlight warmed the metal frame enough to shift the gear alignment.",
      prompt: "The passage is primarily organized as:",
      choices: [
        { id: "a", text: "a series of attempted explanations leading to a discovery." },
        { id: "b", text: "a comparison of two equally successful repairs." },
        { id: "c", text: "a list of instructions for replacing a clock motor." },
        { id: "d", text: "an argument that museums should avoid sunlight." },
      ],
      expectedSeconds: 70,
      correctChoiceId: "a",
      rationale:
        "The team tests the motor and gears before a measurement reveals the actual cause, creating a problem-solving sequence.",
      content: REVIEW,
    },
  ],
});
